[
    {
        "nrp":"1072001",
        "nama":"Budi",
        "kelas":"A",
        "nilai":98
    },
    {
        "nrp":"1072003",
        "nama":"Cindy",
        "kelas":"A",
        "nilai":70
    }
]