[
    {
        "nrp":"1072001",
        "nama":"Budi",
        "kelas":"A",
        "nilai":98
    },
    {
        "nrp":"1072002",
        "nama":"Andi",
        "kelas":"B",
        "nilai":80
    },
    {
        "nrp":"1072003",
        "nama":"Cindy",
        "kelas":"A",
        "nilai":70
    }
]